[package]
name = "sorbus"
version = "0.1.0"
edition = "2018"

authors = [
    "Aleksy Kladov <aleksey.kladov@gmail.com>",
    "Christopher Durham (CAD97) <cad97@cad97.com>",
]

[dependencies]
erasable = "1.1"
hashbrown = "0.7"
ptr-union = "1.0"
rc-borrow = "1.0"
slice-dst = "1.2"
text-size = "0.99.0-dev.3"
