[package]
name = "sorbus"
version = "0.1.0"
edition = "2018"

authors = [
    "Aleksy Kladov <aleksey.kladov@gmail.com>",
    "Christopher Durham (CAD97) <cad97@cad97.com>",
]

[dependencies]
erasable = "1.1" # public
hashbrown = "0.7"
ptr-union = "1.2"
rc-borrow = "1.1" # public
slice-dst = "1.3" # public
text-size = "0.99" # public
